config/routes.rb
Lecture_Together::Application.routes.draw do

  resources :notegroups

  match 'presentations/new' => 'presentations#new' #, :as => :takenotes
  match 'presentations/:id' => 'presentations#takenotes' #, :as => :takenotes

  match "logout" => 'users#logout'#, :as => :logout

  resources :users
  resources :presentations
  resources :courses
  resources :slides
  resources :notegroup
  match "home" => "home#index"

  get "home/index"

  root :to => 'home#index'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :presentation
  #validates :slidetext

  has_attached_file :image, :styles => {},
    :storage => :s3,
    :s3_credentials => "config/s3_credentials.yaml",
    :path => ":attachment/:id/:style.:extension",
    :bucket => 'Slidee',
    :default_url => '/images/missing_:style.jpg'


end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @slides }
    end
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.json
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(params[:slide])

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, :notice => 'Slide was successfully created.' }
        format.json { render :json => @slide, :status => :created, :location => @slide }
      else
        format.html { render :action => "new" }
        format.json { render :json => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.json
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        format.html { redirect_to @slide, :notice => 'Slide was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @slide.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to slides_url }
      format.json { head :ok }
    end
  end



end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slides.each do |slide| %>
  <tr>
    <td><%= slide.number %></td>
    <td><%= slide.title %></td>
    <td><%= slide.content %></td>
    <td><%= link_to 'Show', slide %></td>
    <td><%= link_to 'Edit', edit_slide_path(slide) %></td>
    <td><%= link_to 'Destroy', slide, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<div id="notice"><%= notice %></div>

<table border="1" style="border-style:solid">
<tr>
  <td>
    <div>
      <%= image_tag @slide.image.url %>
    </div>
  </td>
  
  <td width="50%">
	<div id="examplePadBasic" height="100%" style="height:100%"></div>
  </td>
</tr>
</table>


<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>

	<script type="text/javascript">
    $('#examplePadBasic').pad({'padId':'test','width':'100%','height':'600px','showControls':true});
  </script>