config/routes.rb
Lecture_Together::Application.routes.draw do

  resources :notegroups

  match 'presentations/new' => 'presentations#new' #, :as => :takenotes
  match 'presentations/:id' => 'presentations#takenotes' #, :as => :takenotes

  match "logout" => 'users#logout'#, :as => :logout

  resources :users
  resources :presentations
  resources :courses
  resources :slides
  resources :notegroup
  match "home" => "home#index"

  get "home/index"

  root :to => 'home#index'

end

app/models/notegroup.rb
class Notegroup < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :presentation
  serialize :pads, Array
  attr_accessible :pads

  attr_accessor :users_to_add #this allows us to add multiple users at once - the controller loops through them

  def everyonebutme
    userlist = self.users - [User.current]
  end

  def create_pads
    unless self.pads.nil? #this should only be run once ever

      @ether ||= EtherpadLite.connect('http://slideeetherpad.cloudfoundry.com', 'HwcKLaD2oyADLbX6ZO8ZgA719Du9NA17')
      self.pads = []

      self.presentation.slides.each_with_index do |slide, i|
        padid = "notegroup#{self.id}slide#{slide.id}"
        pad = @ether.pad(padid)
        pad.text = slide.slidetext
        self.pads << padid
      end

      self.save

    end
  end

end

app/controllers/notegroups_controller.rb
class NotegroupsController < ApplicationController
  # GET /notegroups
  # GET /notegroups.json
  def index
    @notegroups = Notegroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @notegroups }
    end
  end

  # GET /notegroups/1
  # GET /notegroups/1.json
  def show
    #require 'etherpad-lite'
    @ether = EtherpadLite.connect('http://slideeetherpad.cloudfoundry.com', 'HwcKLaD2oyADLbX6ZO8ZgA719Du9NA17')
    @notegroup = Notegroup.find(params[:id])
    @notegroup.create_pads
    @group = @ether.group("my_app_group_#{@notegroup.id}")
    #@pads = @group.pads
    # Map the user to an EtherpadLite Author
    author = @ether.author("my_app_user_#{current_user.id}", :name => current_user.fullname)

    ## Get or create a two hour long session for this Author in this Group
    #session[:ep_sessions] ||= {} #this should just happen during login
    #sess = session[:ep_sessions][@group.id] ? ether.get_session(session[:ep_sessions][@group.id]) : @group.create_session(author, 120)
    #if sess.expired?
      #sess.delete
      #sess = @group.create_session(author, 60)
    #end
    #session[:ep_sessions][@group.id] = sess.id
    ## Set the EtherpadLite session cookie. This will automatically be picked up by the jQuery plugin's iframe.
    #cookies[:sessionID] = {:value => sess.id, :domain => "afternoon-dawn-1379.herokuapp.com"}
    file_name = File.basename(@notegroup.presentation.deckoriginal_file_name, File.extname(@notegroup.presentation.deckoriginal_file_name));

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @notegroup }
      format.pdf do
        render :pdf           => file_name,
               :layout        => 'pdf.html', # use 'pdf.html' for a pdf.html.erb file
               :show_as_html  => params[:debug].present?,
               :page_size     => 'letter'
               #:exe_path => "/usr/bin/wkhtmltopdf"
               #:wkhtmltopdf   => "/usr/bin/wkhtmltopdf" # path to binary

      end
    end
  end

  # GET /notegroups/new
  # GET /notegroups/new.json
  def new
    @notegroup = Notegroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @notegroup }
    end
  end

  # GET /notegroups/1/edit
  def edit
    @notegroup = Notegroup.find(params[:id])
    @users = User.all - @notegroup.users
  end

  # POST /notegroups
  # POST /notegroups.json
  def create
    @notegroup = Notegroup.new(params[:notegroup])
    @notegroup.users << current_user
    @notegroup.create_pads
    respond_to do |format|
      if @notegroup.save
        format.html { redirect_to @notegroup, :notice => 'Notegroup was successfully created.' }
        format.json { render :json => @notegroup, :status => :created, :location => @notegroup }
      else
        format.html { render :action => "new" }
        format.json { render :json => @notegroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notegroups/1
  # PUT /notegroups/1.json
  def update
    @notegroup = Notegroup.find(params[:id])
    @notegroup.users << User.find(params[:notegroup][:users_to_add]) unless params[:notegroup][:users_to_add].empty?

    respond_to do |format|
      if @notegroup.update_attributes(params[:notegroup])
        format.html { redirect_to(:action => "edit", :notice => 'Notegroup was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @notegroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notegroups/1
  # DELETE /notegroups/1.json
  def destroy
    @notegroup = Notegroup.find(params[:id])
    @notegroup.destroy

    respond_to do |format|
      format.html { redirect_to notegroups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/notegroups_helper.rb
module NotegroupsHelper
end

app/views/notegroups/_form.html.erb
<h4>Invite a Friend</h4>
<div class="subsection">

<%= form_for(@notegroup) do |f| %>
  <% if @notegroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notegroup.errors.count, "error") %> prohibited this notegroup from being saved:</h2>

      <ul>
      <% @notegroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#= f.select :users_to_add, options_for_select(@users),{},{ :multiple => true, :size => 10 }%>
  <%= f.collection_select :users_to_add, @users, :id, :fullname, {:prompt => "Who?"},{}%>

  <div class="actions" style="display:inline;">
    <%= f.submit "Add", :class => "roundedcornersbutton orangebutton", :style => "display:inline;"%>
  </div>
<% end %>
</div>

app/views/notegroups/_slidewithnote.html.erb
<div id="box<%=slidewithnote.id%>" class="box boxright" style="left:150%">

  <div class="colnote">
    <%#<div class="addfriends">%>
      <%#= link_to 'ADD FRIENDS', edit_notegroup_path(@notegroup) %>
    <%#</div>%>
  <div class="etherpaddiv" id="<%=@notegroup.pads[slidewithnote_counter] %>" style="float:right; width:100%; height:100%">
<%#
  http://etherpad-local.com:9001
  http://beta.etherpad.org
%>
    </div>
  </div>

  <div class="colslide" style="border: 1px solid black;">
    <%= image_tag slidewithnote.image.url, :style => "max-width:100%; max-height:100%;"%>
  </div>

</div>

app/views/notegroups/_slidewithnote.pdf.erb
<div class="page">
  <div class="slidenum">
    Slide <%= @slide_number.to_s %>
  </div>
	<% @slide_number += 1 %>
  <div class="slide">
    <%= image_tag slidewithnote.image.url, :style => "width:100%;"%>
  </div>
  <div class="notes">
  <% epad = @ether.pad("notegroup"+notegroup.id.to_s+"note"+slidewithnote.id.to_s) %>
  <%= epad.html.html_safe %>
  </div>
</div>

app/views/notegroups/edit.html.erb
<div class="narrowcontentleft">
  <%#= button_to "Return to Notetaking", @notegroup, :method => "get", :class => "roundedcornersbutton orangebutton"%>
  <%#</br> %>

  <h3><%=link_to(@notegroup.presentation.deckoriginal_file_name, @notegroup)%></h3>
  </br>
  <h4>Friends in <%=@notegroup.presentation.deckoriginal_file_name%></h4>
        <div class="subsection" style="overflow:auto; max-height:300px;">
          <% if @notegroup.everyonebutme.empty?%>
            <div style="color:silver;">Nobody</div>
          <%else%>
            <% @notegroup.everyonebutme.each do |user|%>
              <li><%= user.fullname %></li>
              <% end %>
          <%end%>
        </div>

        <%= render 'form' %>

  <div style="float:right; clear:both; padding: 0px 5px;">
    <%#= button_to "x Delete", new_presentation_path, :method => "get", :class => "roundedcornersbutton redbutton", :id => "id_btnpolls" %>
  </div>
</div>

<div class="narrowcontentright roundedcornersbox">
Don't see a friend? They probably haven't signed into Slidee yet. As soon as they do, a Slidee-user will be created and they'll show up here after you refresh.
</div>

app/views/notegroups/index.html.erb
<h1>Listing notegroups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notegroups.each do |notegroup| %>
  <tr>
    <td><%= link_to 'Show', notegroup %></td>
    <td><%= link_to 'Edit', edit_notegroup_path(notegroup) %></td>
    <td><%= link_to 'Destroy', notegroup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notegroup', new_notegroup_path %>

app/views/notegroups/new.html.erb
<h1>New notegroup</h1>

<%= render 'form' %>

<%= link_to 'Back', notegroups_path %>

app/views/notegroups/show.html.erb
<div id="notice"><%= notice %></div>

<div style="position:absolute; top:7px; right:460px; height:25px;">
  <input type="button" value="←" class="roundedcornersbutton whitearrowbutton" onClick="previousslide();" >
  <input type="button" value="→" class="roundedcornersbutton whitearrowbutton" onClick="nextslide();">
  <span style="position: relative; top:4px;"><%= link_to image_tag("noun_project_1257.svg", :size => "17x17"), edit_notegroup_path(@notegroup)%></span>
  <%= link_to "Download PDF", notegroup_path(@notegroup, :format => "pdf", :target => '_blank') %>

</div>

<div id="container">
  <%= render :partial => "notegroups/slidewithnote", :collection => @notegroup.presentation.slides, :locals => {:notegroup => @notegroup} %>
</div>

<script>
  username = "<%= User.current.fullname %>";
</script>

app/views/notegroups/show.pdf.erb
  <body onload='number_pages'>
    <div class="firstpage" id="firstpage">
      <h1 class="slidee">Slidee Class Notes</h1>
      <h1 class="title"><%= @notegroup.presentation.deckoriginal_file_name %></h1>
      <h3 class="dl_time">Downloaded <% time = Time.new %><%= time.strftime("%B %d, %Y") %></h1>
      </br>
      </br>
    <% if !@notegroup.everyonebutme.empty?%>
      <h2 class="username" style="font-weight:normal;"><span style="font-weight:bold"><%= User.current.fullname %></span> with</h2>
      <p class="collaborators">
      <ul>
      <% @notegroup.everyonebutme.each do |user|%>
        <li><%= user.fullname %></li>
      <% end %>
      </ul>
      </p>
    <% else %>
      <h2 class="username"><%= User.current.fullname %></h2>
    <%end%>

    </div>
    <div id="container">
	    <% @slide_number = 1 %>
      <%= render :partial => "notegroups/slidewithnote", :collection => @notegroup.presentation.slides, :locals => {:notegroup => @notegroup} %>
    </div>
  </body>