config/routes.rb
Lecture_Together::Application.routes.draw do

  resources :notegroups

  match 'presentations/new' => 'presentations#new' #, :as => :takenotes
  match 'presentations/:id' => 'presentations#takenotes' #, :as => :takenotes

  match "logout" => 'users#logout'#, :as => :logout

  resources :users
  resources :presentations
  resources :courses
  resources :slides
  resources :notegroup
  match "home" => "home#index"

  get "home/index"

  root :to => 'home#index'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  require 'RMagick'
  include Magick

  belongs_to :course
  has_one :slidedeck

  has_many :slides, :dependent => :destroy
  has_many :users
  has_many :notegroups
  #has_attached_file :deck #we'll have to convert some deckoriginals to pdf first, we'll use this later
  has_attached_file :deckoriginal,
                    :styles => {
                      :pdf => {
                        :format => "pdf",
                        :processors => [:docsplit_pdf]
                      }
                    }
  #validates_attachment_content_type :deckoriginal, :content_type => ['application/pdf'], :if => deckoriginal_attached?
  #after_deckoriginal_post_process :create_slides
  #validates :deckoriginal, :attachment_presence => true
  validates_attachment_presence :deckoriginal
  #validates_attachment_content_type :deckoriginal, :content_type => ['application/pdf'], :message => "must be PDF."






  def create_pads(user)

  end

  def join_pads(user)

  end

  def create_slides
    #TODO @presentation.slidedeck ---this ought to work but doesn't yet - I must've messed up relationships?
    pdflocation = self.deckoriginal.url(:pdf).gsub(/\?.*$/,"") #strips off the trailing random digits (from paperclip)
    pdflocation_absolute = Rails.root.to_s + "/public" + pdflocation
    basename = File.basename(pdflocation, '.*')
    temporary_dir = Dir.tmpdir

    # Extract Text Into An Array
    Docsplit.extract_text(pdflocation_absolute, :output => temporary_dir)
    texts = File.open(File.join(temporary_dir, "#{basename}.txt")).read #we can predict how it'll be formatted~
    textarray = texts.split("\f", -1) # \f is "flood page" or "clear everything from the page" = "newpage" in pdf speak
                                      # -1 say to not omit null strings. We need them for counting at least~
    # Extract Images Into An Array
    Docsplit.extract_images(pdflocation_absolute, :size => "1000x", :format => :jpg, :output => temporary_dir)

    # Create Slides out of Text and Images! :D
    textarray.each_with_index do |text, i|
      #sometimes there are more text than images - we can drop the last nil text if that's there
      if File.exists?(File.join(temporary_dir, "#{basename}_#{i+1}.jpg"))
        Slide.create(:presentation => self, :image => File.open(File.join(temporary_dir, "#{basename}_#{i+1}.jpg")), :slidetext => text)
      end
    end

    #deck = ImageList.new('public' + self.deckoriginal.url(:pdf).gsub(/\?.*$/,""))

    #deck.each { |slide|
      #temporaryfile = Tempfile.new("my_picture")
      #slide.write("jpeg:" + temporaryfile.path) #writes the slideimage to a temporary file
      ##location = "app/assets/presentations/" + image.hash.to_s + ".jpg" 
      ##slide.write(location)
      #Slide.create(:presentation => self, :image => temporaryfile)
    #}
  end
  private

#pages => slides
  #:asset => :deckoriginal

  #def make_pages
    #if valid?
      #Paperclip.run('convert', "-quality #{Page::QUALITY} -density #{Page::DENSITY} #{deckoriginal.queued_for_write[:original].path} #{deckoriginal.queued_for_write[:original].path}%d.png")
      #images = Dir.glob("#{deckoriginal.queued_for_write[:original].path}*.png").sort_by do |line|
        #line.match(/(\d+)\.png$/)[1].to_i
      #end

      #images.each do |page_image|
        #slides.build(:deckoriginal => File.open(page_image))
      #end
      #FileUtils.rm images
    #end
  #end


end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @presentations }
    end
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    @presentation = Presentation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @presentation }
    end
  end

  # GET /presentations/new
  # GET /presentations/new.json
  def new
    @presentation = Presentation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @presentation }
    end
  end

  # GET /presentations/1/edit
  def edit
    @presentation = Presentation.find(params[:id])
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(params[:presentation])
    
    respond_to do |format|
      if @presentation.save
        @presentation.update_attributes(:course => Course.last) #maybe this should be a hidden field in the form
        @presentation.create_slides #creates all slides (with images and text stored in each slideobject)
        @notegroup = Notegroup.new(:presentation => @presentation)
        @presentation.notegroups << @notegroup
        current_user.notegroups << @notegroup
        format.html { redirect_to @notegroup }#, :notice => 'Presentation was successfully created.'
        format.json { render :json => @notegroup, :status => :created, :location => @notegroup }
      else
        format.html { render :action => "new" }
        format.json { render :json => @notegroup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /presentations/1
  # PUT /presentations/1.json
  def update
    @presentation = Presentation.find(params[:id])

    respond_to do |format|
      if @presentation.update_attributes(params[:presentation])
        format.html { redirect_to @presentation, :notice => 'Presentation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @presentation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation = Presentation.find(params[:id])
    @presentation.destroy

    respond_to do |format|
      format.html { redirect_to presentations_url }
      format.json { head :ok }
    end
  end

  def takenotes
    require 'etherpad-lite'
    @presentation = Presentation.find(params[:id])
    @slidenumber = params[:slidenumber] ? params[:slidenumber].to_i : @presentation.slides.first.id
    @slide = Slide.find(@slidenumber)
    ether = EtherpadLite.connect(:local, '6f8uC4DjXpYgtv12uHInl1jFkmGotYr9')
    @pad = ether.pad('somepad' + @slidenumber.to_s)
    #@pad.text = "This is what my locally hosted pad's text contents are. That other pad is hosted on beta.etherpad.net"


    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @presentation }
    end
  end

end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= form_for(@presentation) do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @presentation.errors.full_messages.each do |msg| %>
        <%unless msg == "Uploaded file name can't be empty"%>
        <%#it's really hard to deal with paperclip errors. We need a more elegant way to do this :/%>
          <li><%= msg %></li>
        <%end%>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.file_field :deckoriginal %>
  </div>

  <div class="actions">
    <%= f.submit "Upload" %>
    <%#:onclick => "this.disabled=true; showMe('loading');" %>
    </br></br></br>
    After uploading, invite friends to collaborate with by pressing the <%=image_tag("noun_project_1257.svg", :size => "15x15")%> button.
  </div>
  
 <div id="loading" class="loadinginprogress">
   <%= image_tag "ajax-loader.gif" %>
 </div>
<% end %>

app/views/presentations/_slidewithnote.html.erb
<div id="box<%=slidewithnote.id%>" class="box boxright" style="left:150%">
  <div class="colslide "style="float:left;">
    <%= image_tag slidewithnote.image.url, :width => "100%"%>
  </div>
  <div class="colnote">
    <div id="note<%=slidewithnote.id%>" style="float:right; width:100%; height:100%">
   <iframe class="etherpadnote" id="etherpadnote<%=slidewithnote.id%>" src="http://etherpad-local.com:9001/p/<%=slidewithnote.id%>?showControls=true&amp;showChat=true&amp;showLineNumbers=false&amp;useMonospaceFont=false&amp;userName=caseywatts&amp;noColors=false&amp;hideQRCode=false" style="border: 0; width: 100%; height: 100%;"></iframe> 
    </div>
  </div>
</div>

app/views/presentations/_slidewithnotejs.html (another copy).erb
$("#note<%=slidewithnotejs.id%>").pad({'padId':"LectureTogetherNote<%=slidewithnotejs.id%>",'width':'100%','height':'100%','showControls':true,'userName':'caseywatts'});

app/views/presentations/_slidewithnotejs.html (copy).erb
<script type="text/javascript">
var length = <%=slideset.length%>;
var slideset = <%=slideset.to_json%>;

//I preload only the first five slides, wait a second, then do the rest
if (length>=5)
  {
  var i=0;
  for (i=0;i<5;i++)
    {
    $("#note"+ slideset[i]).pad({'padId':("LectureTogetherNote" + slideset[i]),'width':'100%','height':'100%','showControls':true,'userName':'caseywatts'});
    }
  setTimeout(function(){
      for (i=5;i<=length;i++)
        {
        $("#note"+ slideset[i]).pad({'padId':("LectureTogetherNote" + slideset[i]),'width':'100%','height':'100%','showControls':true,'userName':'caseywatts'});
        }
    }
    ,5000
  );
  }
else
  {
  var i=0;
  for (i=0;i<=5;i++)
    {
    $("#note"+ slideset[i]).pad({'padId':("LectureTogetherNote" + slideset[i]),'width':'100%','height':'100%','showControls':true,'userName':'caseywatts'});
    }
    $("#note"+ slideset[i]).css('position', 'absolute');

  }

</script>

app/views/presentations/_slidewithnotejs.html.erb
$("#note<%=slidewithnotejs.id%>").pad({'padId':"LectureTogetherNote<%=slidewithnotejs.id%>",'width':'100%','height':'100%','showControls':true,'userName':'caseywatts'});

app/views/presentations/edit.html.erb
<h1>Editing presentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<div class="narrowcontentleft">
  <h3 style="display:inline;">My Slides</h3>
  <div style="float:right; padding: 0px 5px;">
    <%= button_to "+ Add Slideshow", new_presentation_path, :method => "get", :class => "roundedcornersbutton orangebutton"%>
  </div>
  <div class="subsection">
    <% if User.current.notegroups.empty?%>
            No Slides Yet
    <%else%>
      <% current_user.notegroups.reverse.each do |notegroup| %>
        <div class="item" style="clear:both" onmouseover="document.getElementById('notegroup-edit-<%=notegroup.id%>').style.visibility = 'visible';" onmouseout="document.getElementById('notegroup-edit-<%=notegroup.id%>').style.visibility = 'hidden';">
          <%=image_tag("noun_project_453.svg", :size => "16x10")%>
          <%=link_to notegroup.presentation.deckoriginal_file_name, notegroup %>
          <span id="notegroup-edit-<%=notegroup.id%>" class="hiddenedit"><%=link_to image_tag("noun_project_1257.svg", :size => "15x15"), edit_notegroup_path(notegroup)%></span>
        </div>
      <% end %>
    <% end %>
  </div>

  </br></br>

</div>

<div class="narrowcontentright roundedcornersbox">
  Upload a presentation PDF and invite some friends to take notes with you - in real time!</br></br>
  Or ask a friend to add you to their presentation.</br></br>
  The best size for a notetaking group is usually 2-3 people, depending on the class.</br>
</div>



<%=render :partial => 'layouts/include/footer' %>

app/views/presentations/new.html.erb
<div class="narrowcontentleft">
  <h3>New presentation</h3>
  </br>
  <div class="subsection">
    Only PDFs may be uploaded. </br></br>To use a PPT file with Slidee, follow the instructions to the right.</br></br></br>
    <%= render 'form' %>
  </div>
</div>

<div class="narrowcontentright roundedcornersbox" style ="text-align: left;">
  Uploading and processing may take as long as ~30 sec. </br></br></br>
  <span style="text-decoration:underline;">To convert a PPT file to a PDF</span></br>
  Open it in Powerpoint (or Keynote) and export it.</br></br>
  The export function could be in one of a few places.
  <li style="text-align:left">File... Save as... PDF
  </li>  <li style="text-align:left">File... Save as PDF
  </li>  <li style="text-align:left">File... Export... to PDF
  </li>
</div>

app/views/presentations/show.html.erb
<p id="notice"><%= notice %></p>

  <div id="<%=@slide.id%>" style="float:left; width:100%; height:600px">
    <div class="colslide "style="float:left;">
      <%= image_tag @slide.image.url, :width => "100%"%>
    </div>
   <div class="colnote" style="float:left; width:450px; height:100%">
      <div id="<%=@slide.id%>" style="float:right; width:100%; height:100%"></div>
   </div>
  </div>

	<script type="text/javascript">
    $('#<%=@slide.id%>').pad({'padId':'<%=@slide.id%>','width':'100%','height':'100%','showControls':true});
  </script>

<%= link_to 'Edit', edit_presentation_path(@presentation) %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/takenotes.html.erb
<div id="notice"><%= notice %></div>
<%#<input type="button" value="Next Slide" onClick="nextslide();">%>
<%#<input type="button" value="Previous Slide" onClick="previousslide();">%>
<div id="container">
      <%= render :partial => "presentations/slidewithnote", :collection => @presentation.slides %>
</div>